### ISSUE TITLE
My repo here suddenly gone without notice.

### ISSUE THREAD

**Issue by CrescendoFang** [Magisk-Modules-Repo/submission#115]
the link was: https://github.com/Magisk-Modules-Repo/natrium-mods

the original source is: https://github.com/CrescendoFang/natrium-device-mods

**Comment by Didgeridoohan** [comment]
Might have been an accidental casualty of the recent cleanups... Make a new submission, and may I also suggest that you make a device check at installation and abort if it's not a Xiaomi Mi 5S Plus (or otherwise a compatible device).

**Comment by CrescendoFang** [comment]
@Didgeridoohan lol I was uploading new changes when the GH desktop complained that there's no repo...

**Comment by CrescendoFang** [comment]
@Didgeridoohan alao since I'm still new in Magisk module making, could you please help me to make a device check as I don't know how to do it. Thanks.

**Comment by Didgeridoohan** [comment]
Make a check for the prop ro.product.name (if I remember correctly). If it matches "natrium" continue with the install, otherwise abort.

**Comment by CrescendoFang** [comment]
@Didgeridoohan I'll try & update the sources if it's working...

thank you so much..
