### ISSUE TITLE
[Submission] Stock Experience mod for sanders

### ISSUE THREAD

**Issue by marshmello61** [Magisk-Modules-Repo/submission#118]
https://github.com/marshmello61/Stock-Experience

**Comment by marshmello61** [comment]
Hey, As You told me to set the detection for the device. Please can you
guide me with the commands that can be useful to edit in config.sh ?

**Comment by skittles9823** [comment]
Grep build.prop for the correct prop that shows the device name. Its ro.build.product iirc. Then place that in an if statement then, in the else make it exit with a ui_print saying the device isn't compatible.

**Comment by skittles9823** [comment]
Oh also, I just remembered. You should probably combine your modules into one. Since they basically do the same thing. Just check XDA and you'll see my help thread, in the second post it shows a tutorial post for how to take volume key input for choices.

**Comment by marshmello61** [comment]
I now changed the config.sh in order to detect the device. If it's not sanders then it will abort.
But I can't get that how to set the volume key detection for the selection of mods even after reading your xda thelp thread. Can u please explain me.

**Comment by skittles9823** [comment]
Did you have a look in the post for a link to the tutorial post?

**Comment by marshmello61** [comment]
Yes. Offcourse

**Comment by skittles9823** [comment]
Then that should be enough info to implement. (It is a lot easier when using the Unity template btw)

**Comment by marshmello61** [comment]
Yes. I understood how to do the keytest, but just i don't understand is
where to put my files in modules coz both the names of changing is just
same i.e., mixer_paths.xml .
Also I don't understand that where to put my file location in the keytest.
Can u please help me giving codes for my files ?? Please

**Comment by skittles9823** [comment]
Have a look at the icesound module for how it uses the keytest and look at Sauron for how it patches mixer_paths.xml

**Comment by marshmello61** [comment]
Thanks for the information .
Really helpful
