### ISSUE TITLE
[Submission] Brand new Motomusic app for all devices

### ISSUE THREAD

**Issue by marshmello61** [Magisk-Modules-Repo/submission#120]
https://github.com/marshmello61/Motomusic-Magisk

**Comment by marshmello61** [comment]
But for using app systemizer module - you must have this app installed. I know that this app can be found easily but some peoples really don't know how to find it. So it makes the reason to add it in the repo. Also this app will be updated Regularly after moto officially updates.

**Comment by skittles9823** [comment]
Still, an xda thread sounds more suitable for this in my opinion. At least until categories are implemented.

**Comment by marshmello61** [comment]
Yess. It sounds more suitable, but from xda thread people have to first
download the module, then go to magisk manager and finally install module
by pressing module "+" button.
But if you put this to the repo people who want the moto music as their
app, can directly search on downloads under mm and then install. No need to
do all the things to download from xda then head to mm, etc...

**Comment by yochananmarqos** [comment]
The app doesn't need to be installed to systemize it, you can also choose an APK from storage.

**Comment by marshmello61** [comment]
Yes, but u still need the apk file. Which is really difficult for some
peoples that did not know how to find the apk on google also moto is not
gonna release it on play store.

**Comment by marshmello61** [comment]
Leaving that point. Rhyse first was saying that why to add this module to
the magisk repo, if people can make it the system app by app systemizer. I
see that there is also vanced youtube available online so people can't just
download it from there and make it system app by app systemizer, why add
that to the magisk repo ??

**Comment by marshmello61** [comment]
Thanks for the information..
It was really helpful
