### ISSUE TITLE
[Submission] Urdu Font - Mehr Nastaliq

### ISSUE THREAD

**Issue by kamilmirza** [Magisk-Modules-Repo/submission#140]
https://github.com/kamilmirza/Urdu-MehrNastaliq-font

**Comment by kamilmirza** [comment]
any update on this?

**Comment by skittles9823** [comment]
Fonts are currently on hold as they were kind of flooding the repo before. 

The current recommendation is to use midnight core to apply fonts, but we are hoping for some sort of category system to sort fonts and other specialized modules into.

**Comment by ATechnoHazard** [comment]
Closing issue for now.
