### ISSUE TITLE
about modules TikTok Unlock In China 

### ISSUE THREAD

**Issue by user1121114685** [Magisk-Modules-Repo/submission#19]
@sjayminsgithub 
https://github.com/Magisk-Modules-Repo/submission/issues/18

> > This kind of modules are currently debated and I will have to hold approval for now.
> 
> Meanwhile, description in module.prop is still in Chinese, please translate that to English. Also, please re-write README like, first all in English and then all in Chinese, so it's easier for user to read that. Let me know once you have done that.
> 
> I will let you know about final decision.
> 
> Jaymin Suthar,
> Repo Moderator.
> 
> NOTE: If you respond within 48 hours, this submission will be rejected.

may i say that it's not required by the module.prop magisk group that the languege must be english ?but i can change README into first all in chinese and then all in english. afater all ,this module is only available for chinese and that could be more user-friendly.

**Comment by sjayminsgithub** [comment]
OK, I should allow module.prop
Please put English first in README, and let Chinese people know description in Chinese is below.
BTW, you could have commented in the previous issue.

**Comment by user1121114685** [comment]
@sjayminsgithub your say: NOTE: If you respond within 48 hours, this submission will be rejected.

**Comment by user1121114685** [comment]
@sjayminsgithub README it's change ,please remember to notify me

**Comment by sjayminsgithub** [comment]
OK, I will notify you as soon as a decision is announced.
