### ISSUE TITLE
[Submission] YellowBlob Resurrector

### ISSUE THREAD

**Issue by motorailgun** [Magisk-Modules-Repo/submission#218]
https://github.com/motorailgun/yellowblob-resurrector

**Comment by JohnFawkes** [comment]
what does this do that blobemoji doesnt? we have a blob emoji enabler in the repo already

John Fawkes
Repo Moderator

**Comment by motorailgun** [comment]
Yes, this module just use Android M and N Emojis, and doesn't use original Emojis.

**Comment by topjohnwu** [comment]
A new Magisk installer format is now enforced. Please carefully read through the [updated documentations](https://topjohnwu.github.io/Magisk/guides.html) to learn how to migrate to the new format. Update your module to the new format and submit again, thanks!
