### ISSUE TITLE
[Submission] Pixel3 VoLTE/VoWifi Enabler for TW

### ISSUE THREAD

**Issue by protonchang** [Magisk-Modules-Repo/submission#264]
https://github.com/protonchang/Pixel3-VoLTE-for-TW

**Comment by topjohnwu** [comment]
A new Magisk installer format is now enforced. Please carefully read through the [updated documentations](https://topjohnwu.github.io/Magisk/guides.html) to learn how to migrate to the new format. Update your module to the new format and submit again, thanks!
