### ISSUE TITLE
[Submission] FeraDroid Engine

### ISSUE THREAD

**Issue by feravolt** [Magisk-Modules-Repo/submission#265]
https://github.com/feravolt/FeraDroid-Engine

**Comment by feravolt** [comment]
Hello. Sorry for bothering, but why it takes so long to make a desicion on mod submission? If there are any issues with my mod, please let me know and I will try to fix 'em if any. Thanks.

**Comment by Didgeridoohan** [comment]
Examining modules can take some time, especially complicated ones... If no moderator has the time, it'll have to wait.

I'm currently not in a position to make any thorough examination, but I took a quick look. Looks like you're mounting /system rw and doing direct alterations, something that goes against the whole point of Magisk systemless modifications. Is that something you could take care of?

**Comment by feravolt** [comment]
> 
> 
> Examining modules can take some time, especially complicated ones... If no moderator has the time, it'll have to wait.
> 
> I'm currently not in a position to make any thorough examination, but I took a quick look. Looks like you're mounting /system rw and doing direct alterations, something that goes against the whole point of Magisk systemless modifications. Is that something you could take care of?

Hello. Thanks for responce. My tweak-pack support both methods systemless & direct system mode for those who's not on magisk. An universal installer, something similar to "unity" templates, but i write all from scratches by myself. But you're right - it does mount system as rw - but if it detects magisk.img - rest operations are done totally systemless (there are changes on data partitions only). The thing i can do with this is to move 'mount system rw' to the part where magisk is not detected and hope this will totally fix all issues. Updating repo ASAP. Thanks in advance.

**Comment by skittles9823** [comment]
Detecting `data/adb/magisk.img` won't work for Magisk Canary users as Magisk no longer uses it in 18.2 the better thing to check for would be the existence of the `/data/adb/magisk/` directory.

**Comment by feravolt** [comment]
> 
> 
> Detecting `data/adb/magisk.img` won't work for Magisk Canary users as Magisk no longer uses it in 18.2 the better thing to check for would be the existence of the `/data/adb/magisk/` directory.

OK. I didn't know that on dev builds of magisk this will not work anymore, thanks. I will update my code with your mentioned method ASAP.

**Comment by topjohnwu** [comment]
A new Magisk installer format is now enforced. Please carefully read through the [updated documentations](https://topjohnwu.github.io/Magisk/guides.html) to learn how to migrate to the new format. Update your module to the new format and submit again, thanks!
