### ISSUE TITLE
[Submission] Fluence Full-Ultra-High-Definition Patch

### ISSUE THREAD

**Issue by Miustone** [Magisk-Modules-Repo/submission#266]
https://github.com/Miustone/FFUHD

Cleanup of: https://github.com/Magisk-Modules-Repo/submission/issues/232
Hope there are no more Issues with My Patch. Best Regards from Germany!

**Comment by Didgeridoohan** [comment]
Looks like you've made the installer into a pure Aroma installer. That won't install from the Manager, so why should it be in the Magisk repo?

**Comment by Miustone** [comment]
I think It would help the Users a lot to get Releases over a central Place on Android, without forcing them to use 3rd Party Services like Google, Mega or others. Besides that is Magisk giving a nice overview in the Download Section of what Users get from My Module, and everything else can still be handled over the Magisk App. Like disabling, removing and to see which Version is actually installed.
AROMA has a included Terminal and File Manager which is pretty unique actually. That alone is worth the step over TWRP instead of using the App in My Eyes. We all have to reboot when we install Modules in the Magisk Manager, so it's not even a extra step to directly boot into TWRP from the Module Tab in Magisk (3Dot Menu gives us that Option). I would also mind to give the Users a Hint that this Modules uses AROMA and needs TWRP. Since i know flashfire for example (Which flashs AROMA without Recovery) am i not even sure if we will never be able to use AROMA within Magisk, maybe does somone manage to include that one Day...

Sorry for My bad English, i could explain me better in German lol. I would really appreciate to be part of this Repo.
Best Regards!

**Comment by Miustone** [comment]
Nice side effect i've noticed today, when i flash with AROMA am i able to uninstall and install in one rush. I don't even have to exit the Installer to do that. Since the System isn't booted like with the APP is there no need for 2 reboots. 1 Reboot at all and the Module is updated. Pretty nice...

**Comment by Didgeridoohan** [comment]
Since this can't even be installed from the Manager it has no business being included in the Magisk repo...

**Comment by Didgeridoohan** [comment]
Oh yeah... The bot is undergoing maintenance. I'll close this manually.
