### ISSUE TITLE
Module not showing up in magisk manager.

### ISSUE THREAD

**Issue by feravolt** [Magisk-Modules-Repo/submission#277]
Hello. Sorry if i write this in a wrong place, but I don't know where to ask else. My module was approved, but **not** showing up in magisk manager. How this can be fixed? Thanks in advance!
https://github.com/Magisk-Modules-Repo/FDE

**Comment by topjohnwu** [comment]
Sorry, there is a bug in Magisk Manager, will fix ASAP
