### ISSUE TITLE
[Submission] Xiaomi Mi A1 Stereo Speaker Mod

### ISSUE THREAD

**Issue by WhatzIt2Ya** [Magisk-Modules-Repo/submission#303]
https://github.com/WhatzIt2Ya/tissotstereomod

**Comment by sjaymin1001** [comment]
@WhatzIt2Ya Incorrect usage of abort() function in install.sh, you're specifying exit code there. I hope you re-read the documentations a few lines above that and fix that.

**Comment by WhatzIt2Ya** [comment]
Fuck you and your magical team. If you don't accept my module, then don't tell me what to fucking fix if you're not going to put it on the magisk-repo anyway. If I have trouble getting the module right, then you can help me on the step how to fucking do it. Not just, "read the documentation", WHEN THERE IS NO FUCKING INFORMATION! IF YOU'RE NOT GOING TO BE NICE, THEN GO FUCK YOURSELF! DON'T KEEP BULLSHITTING ABIUT READ THE MOTHERFUCKING DOCUMENTATION. FUCK YOU AND GOODBYE.

**Comment by topjohnwu** [comment]
@WhatzIt2Ya congrats man, you are the first person to be banned from the organization!
