### ISSUE TITLE
AOSP EXPERIENCE

### ISSUE THREAD

**Issue by zdneseau** [Magisk-Modules-Repo/submission#32]
A module based on my personal use, and few items that I cherry-picked from other modules to suit this module to almost pixel-like.

**Comment by skittles9823** [comment]
Please read the readme for information on how to submit a module before opening an issue. Thanks.

**Comment by Didgeridoohan** [comment]
I'm just gonna go ahead and close this...

**Comment by sjayminsgithub** [comment]
@zdneseau If you don't even know how to submit a module, your module will never be approved.
