### ISSUE TITLE
[Submission] axet's Call Recorder

### ISSUE THREAD

**Issue by FeralHedgehog** [Magisk-Modules-Repo/submission#332]
https://github.com/FeralHedgehog/axet-call-recorder

**Comment by Zackptg5** [comment]
[Terminal systemizer](https://github.com/Magisk-Modules-Repo/terminal_systemizer) module can already do this (it and turn any app into a system app like this) unless I'm missing something special about this mod

**Comment by FeralHedgehog** [comment]
Didn't know about the Systemizer. I see how it makes more sense as a solution compared to systemizing individual apps. Thanks and sorry for wasting your time!
