### ISSUE TITLE
[Submission] Circular Std Font for Magisk

### ISSUE THREAD

**Issue by wasefali** [Magisk-Modules-Repo/submission#36]
https://github.com/wasefali/Circular-Std-Font.git

**Comment by OldMidnight** [comment]
Permissions need to have been set in config.sh before it was approved

**Comment by sjayminsgithub** [comment]
@OldMidnight I see nothing wrong, default permissions should work for fonts.

**Comment by OldMidnight** [comment]
As long as it's 644 its fine, using a client so can't tell, if it is, my bad:sweat_smile:
