### ISSUE TITLE
DJY-Nethunter-Magisk-Modules

### ISSUE THREAD

**Issue by johanlike** [Magisk-Modules-Repo/submission#393]
***Please Add https://github.com/johanlike/DJY-Nethunter-Magisk-Modules***

**Comment by yochananmarqos** [comment]
Lucky Patcher will not be allowed in the repo.

**Comment by johanlike** [comment]
Lucky-patch has been removed. Please add it from the new

**Comment by yochananmarqos** [comment]
Why does the repo name differ from the module id and name? Nethunter-Magisk-Modules does not describe what it is and will not be accepted as such. Something like Nethunter-Firmware-and-Apps is more fitting. 

Please check the [submission](https://github.com/Magisk-Modules-Repo/submission#submission) rules again and resubmit when it's compliant.
