### ISSUE TITLE
[Question] systemless-google-emojis

### ISSUE THREAD

**Issue by Helmasaur** [Magisk-Modules-Repo/submission#396]
Can I please know why it has been rejected? Thank you!
https://github.com/Helmasaur/systemless-google-emojis

**Comment by JayminSuthar1001** [comment]
@Helmasaur Link me to submission issue and I'll try to help you.

**Comment by Helmasaur** [comment]
This is: https://github.com/Magisk-Modules-Repo/submission/issues/368 . Thank you if you can give an answer :D

**Comment by JayminSuthar1001** [comment]
It seems like none of moderators could review your module withing time-limit of 21 days. Submit it again so that I can review it.

**Comment by Helmasaur** [comment]
Alright, I'll do that, thanks :)

**Comment by JayminSuthar1001** [comment]
I'll close it then.
