### ISSUE TITLE
{Submission] Xtrememusic-Magisk

### ISSUE THREAD

**Issue by ibay770** [Magisk-Modules-Repo/submission#403]
Edited repo to Magisk standards, and added more info to readme.

**Comment by yochananmarqos** [comment]
Please read the submission guidelines: https://github.com/Magisk-Modules-Repo/submission

**Comment by yochananmarqos** [comment]
Also you're using an old template. Please update to the newest before submitting again.

**Comment by Didgeridoohan** [comment]
Is this your work, or are you just posting someone else's module to the repo?

**Comment by ibay770** [comment]
I am posting someone else module to the repo. Antonio made it and wants more exposure so I spoke with him about adding it to the repo. He said he doesn't have time to do it, but hes happy if I give it a shot and give him accreditation which I'm doing to the best of my ability. 

⁣Get TypeApp for Android ​
