### ISSUE TITLE
[Submission] OnePlus Weather and Widget

### ISSUE THREAD

**Issue by tfae** [Magisk-Modules-Repo/submission#411]
https://github.com/tfae/oneplus_weather_and_widget

**Comment by MarcAnt01** [comment]
There's already Oxy-ify allowing their installation and having them in system has no advantage

**Comment by tfae** [comment]
> There's already Oxy-ify allowing their installation and having them in system has no advantage

You're right. By the time I made it the Oxy-fi didn't let to choose what we want. Now this module is kinda pointless.
