### ISSUE TITLE
[Submission] Lawnchair v1 and LawnFeed systemlessly

### ISSUE THREAD

**Issue by dark-basic** [Magisk-Modules-Repo/submission#43]
https://github.com/dark-basic/Lawnchair-lawnfeedv1

**Comment by deletescape** [comment]
Why would this be needed? In Lawnchair v1 there is absolutely no advantage to running it as a system app, at least none that I could think of

**Comment by skittles9823** [comment]
Also, like lawnfeed isn't needed if you use the GitHub or telegram versions of v1 since its built as a debug app.

This module doesn't really make sense in my opinion, so I'm going to wait for a response from you to try to convince me why it should be on the repo.

**Comment by dark-basic** [comment]
Well, I thought it was a good idea to have it like that, but seeing that it is possibly better not to publish it. Better close the thread
