### ISSUE TITLE
[Submission] Bromite SystemLess WebView

### ISSUE THREAD

**Issue by alexa-v2** [Magisk-Modules-Repo/submission#465]
https://github.com/bromite/bromitewebview

This is the new official repository of the existing bromite systemless webview. As per @csagan5 request the repo is now hosted under the Bromite organization, so this one needs forked and the old one deleted

Also per his request, not only I need write access: @csagan5 does too

**Comment by JayminSuthar1001** [comment]
The owner should have admin access, ask them and he will be able to invite all of the team.

**Comment by Didgeridoohan** [comment]
@alexa-v2 You can delete the old repo yourself, that's way easier... You're the one who submitted it, right? So you have admin access to it.

**Comment by alexa-v2** [comment]
@didgeridoohan but this new one needs forked first, so it doesn't disappear off the repo entirely

**Comment by alexa-v2** [comment]
I need to switch which repo is forked from since the project is official and whatnot now
As soon as this one is live I'll delete the old

**Comment by topjohnwu** [comment]
@alexa-v2 give @csagan5 write (or admin) permission to the repo
@csagan5 just force push the repo to whatever your current version is

**Comment by topjohnwu** [comment]
@csagan5 I just added you as an admin, please check your email and you can take over the repo as you wish

**Comment by csagan5** [comment]
@topjohnwu thanks, that worked. I deleted the old one (it was also bloated with old deleted binaries, ~364MB). Can somebody in the `Magisk-Modules-Repo` organisation fork it from https://github.com/bromite/bromitewebview now?

This way we can keep that as the upstream (easier for PRs, issues etc).

Thanks

**Comment by Didgeridoohan** [comment]
@csagan5 The modules in the Magisk repo aren't forks of any upstream repositories. Modules in the repo are cloned on submission and have nothing to do with the original repo. Details:
https://github.com/Magisk-Modules-Repo/submission/blob/master/README.md#submission
https://github.com/Magisk-Modules-Repo/submission/blob/master/README.md#notes

Now that you deleted the existing Magisk repo you have nothing to work with (pushing your code to it as @topjohnwu suggested)... If you still want to maintain a Magisk repo copy of your official repo I suggest you create a new submission ticket.

**Comment by csagan5** [comment]
@alexa-v2 there cannot be an official upstream, see above. Please re-submit it independently, I am sorry but there will not be anything officially endorsed about this module.

Feel free to fork the repository I created or your version, I will delete it in a few days.

**Comment by alexa-v2** [comment]
@csagan5
What about your original idea? I fork yours to the repo, and submit PRs to yours. I always knew this was cloned not forked, I didn't know you didn't

And endorsement does not require you to own the repo, I can always add you as a collaborator

**Comment by alexa-v2** [comment]
@csagan5 see the cross referenced issues

I still think this can be made to work. Just not easily. And as a developer yourself, I feel certain that you know nothing has an easy solution

**Comment by csagan5** [comment]
> I fork yours to the repo, and submit PRs to yours.

Sure, let's try.
