### ISSUE TITLE
[Submission] MIUICamera Port for ZenFone Max Pro M1

### ISSUE THREAD

**Issue by gokul1630** [Magisk-Modules-Repo/submission#471]
https://github.com/gokul1630/MIUICamera-Port-for-Asus-ZenFone-Max-Pro-M1

**Comment by JayminSuthar1001** [comment]
Hi Gokul,

Why are you using absolute path for *vendor* [here](https://github.com/gokul1630/MIUICamera-Port-for-Asus-ZenFone-Max-Pro-M1/blob/master/install.sh#L163) ? Are you sure about the working directory when `custom_variables` is executed ?

Why are using `break` within `if...else` construct ? You need to take a crash course on shell scripting.

Check [here](https://github.com/Magisk-Modules-Repo/IPControl/blob/master/install.sh#L189-L197) too. There's a flaw in current `abort` function provided *util_functions.sh*, you need to fix that too in your module.

Closing this for now. Once you have been through needy things, open it again !
