### ISSUE TITLE
WMfonts

### ISSUE THREAD

**Issue by Stardusstt** [Magisk-Modules-Repo/submission#537]
Full weight and macOS fonts patch for Android devices .
https://github.com/Stardusstt/WMfonts/tree/master/Android/WMfonts

**Comment by JayminSuthar1910** [comment]
@Stardusstt 
First of all, the github link must point to a complete module repository, not a folder in a repo that serves as module.
And then, you must use the newer template to make your module.

But these will still not help as font modules are not accepted in the Repo.
