### ISSUE TITLE
[Resubmission]Pixel 4/4XL motion sensor mod with OsloBridger app

### ISSUE THREAD

**Issue by jcarletto27** [Magisk-Modules-Repo/submission#571]
https://github.com/jcarletto27/magisk_module_motionsense_mod

**Comment by jcarletto27** [comment]
Why does the bot auto close after 21 days?

**Comment by Tomy0498** [comment]
> https://github.com/jcarletto27/magisk_module_motionsense_mod

**Comment by jcarletto27** [comment]
update?

**Comment by Tomy0498** [comment]
> ¿actualizar?

**Comment by jcarletto27** [comment]
@topjohnwu Can you please provide a reason for closing my submission?

**Comment by msfjarvis** [comment]
> @topjohnwu Can you please provide a reason for closing my submission?

https://github.com/Magisk-Modules-Repo/submission/issues/581#issuecomment-569447027
