### ISSUE TITLE
[Resubmission]GPS Joystick Systemize

### ISSUE THREAD

**Issue by bluehomewu** [Magisk-Modules-Repo/submission#576]
https://github.com/bluehomewu/GPS-Joystick.git

**Comment by yochananmarqos** [comment]
You can systemize the APK's with Terminal App Systemizer.

**Comment by bluehomewu** [comment]
> 您可以使用Terminal App Systemizer對APK進行系統化。

It not work on some device.
Like AB slot(Android 10-SaR)
(ZenFone 5Z)
That I make this module reason.

Please adopt the recommendations.

**Comment by yochananmarqos** [comment]
All your module does is place the APK's in `/system/priv-app`. Terminal App Systemizer does that and sets the proper permissions. If you have an issue with the module, please post in the [XDA support thread](https://forum.xda-developers.com/apps/magisk/module-terminal-app-systemizer-ui-t3585851).
