### ISSUE TITLE
K-Click Switcher

### ISSUE THREAD

**Issue by mikesew1320** [Magisk-Modules-Repo/submission#579]
https://github.com/mikesew1320/K-Click-Switcher.git

**Comment by mikesew1320** [comment]
Why you closed my request?

**Comment by mikesew1320** [comment]
Can u tell me your reason please?

**Comment by msfjarvis** [comment]
> Can u tell me your reason please?

https://github.com/Magisk-Modules-Repo/submission/issues/581#issuecomment-569447027
