### ISSUE TITLE
[Submission]Revoke China Certificates

### ISSUE THREAD

**Issue by hackerchai** [Magisk-Modules-Repo/submission#581]
[https://github.com/hackerchai/Magisk-Revoke-China-Certs/](url)

**Comment by Zackptg5** [comment]
The link redirects to: https://github.com/Magisk-Modules-Repo/submission/issues/url. It'll need changed to the actual repo

**Comment by topjohnwu** [comment]
Starting from 2019.12.29, new module submissions are required to follow the new module installer format.  Instructions on how to create new modules with the new format is available in this page: [Developer Guides](https://topjohnwu.github.io/Magisk/guides.html). Once you've migrated, you can re-submit your module. Sorry for the inconvenience!
