### ISSUE TITLE
[Submission] dnscrypt-proxy for Android [Extended Version]

### ISSUE THREAD

**Issue by adit** [Magisk-Modules-Repo/submission#583]
https://github.com/adit/dnscrypt-proxy

**Comment by topjohnwu** [comment]
Starting from 2019.12.29, new module submissions are required to follow the new module installer format.  Instructions on how to create new modules with the new format is available in this page: [Developer Guides](https://topjohnwu.github.io/Magisk/guides.html). Once you've migrated, you can re-submit your module. Sorry for the inconvenience!

**Comment by Zackptg5** [comment]
How is this different from the one already in the repo?
https://github.com/Magisk-Modules-Repo/dnscrypt-proxy2

**Comment by Zackptg5** [comment]
Bad timing there :/
