### ISSUE TITLE
Order on 102

### ISSUE THREAD

**Issue by janlubina** [Magisk-Modules-Repo/submission#613]
There is a widespread belief bordering on certainly that the prime numbers are arranged on the axis of numerical chaotic, does not given them apparently no law that would allow us to clearly describe them all. I will try to show in this article "Order on 102", what laws rule and what order prevails among primes, which allows all of them to be clearly described. Whoever reads it to the end will find out what extraordinary order and harmony prevails in the world of prime numbers instead of chaos.

**Comment by ATechnoHazard** [comment]
What the fuck
