### ISSUE TITLE
[Submissions] Selinux Permissiver

### ISSUE THREAD

**Issue by Wahyu6070** [Magisk-Modules-Repo/submission#636]
https://github.com/Wahyu6070/Selinux-Permissiver

**Comment by yochananmarqos** [comment]
Please see [submission guidelines](https://github.com/Magisk-Modules-Repo/submission#what-will-not-be-approved), simple boot scripts will not be accepted.

You can place a script in `/data/adb/service.d/` to accomplish this.

**Comment by Wahyu6070** [comment]
maybe this is simple but useful
