### ISSUE TITLE
[Submission] LineageOS Recorder Installer 

### ISSUE THREAD

**Issue by nonnymoose** [Magisk-Modules-Repo/submission#64]
https://github.com/nonnymoose/lineage-recorder

**Comment by gloeyisk** [comment]
> 
> 
> https://github.com/nonnymoose/lineage-recorder

Where's the recorder app? =D

**Comment by nonnymoose** [comment]
@gloeyisk on the master branch

**Comment by gloeyisk** [comment]
> 
> 
> @gloeyisk on the master branch

Ok, where? =D

**Comment by gloeyisk** [comment]
> 
> 
> @gloeyisk on the master branch

I can't find it :confused:

**Comment by gloeyisk** [comment]
> 
> 
> @gloeyisk on the master branch

What's difference with the default one from ROM?

**Comment by nonnymoose** [comment]
@gloeyisk It's the same recorder app as the default one from Lineage. This module will install it on non-Lineage ROMs, including AOSP-based stock ROMs.

**Comment by VR-25** [comment]
Hmm... 🤔
- How many non-(LOS|-based) ROMs have you tested this on? Did it behave properly?
- Which LOS version was this apk taken from?

**Comment by OldMidnight** [comment]
No comments or commits have been made in the last 4 days, far past the 48 hour cooling period. Closing this.
