### ISSUE TITLE
[Submissions] Brotli

### ISSUE THREAD

**Issue by Wahyu6070** [Magisk-Modules-Repo/submission#640]
https://github.com/Wahyu6070/Brotli

**Comment by Zackptg5** [comment]
This is redundant with an already existing mod, ccbins which has brotli for arm, arm64, x86 and x64. Thanks though!

**Comment by Wahyu6070** [comment]
then you put brotli into your module

**Comment by Zackptg5** [comment]
I already had it but forgot to put it in. You also had an arm64 binary but list arm support

**Comment by Wahyu6070** [comment]
Can you make make_ext4 executables on Android?

**Comment by Zackptg5** [comment]
It was replaced with mke2fs on newer Android versions. Any specific thing you need it for that mke2fs can't do?
