### ISSUE TITLE
Some modules are shipping compiled binaries even though they use GPL-v2/v3 licence.

### ISSUE THREAD

**Issue by YaroST12** [Magisk-Modules-Repo/submission#651]
FeraDroid Engine
https://github.com/Magisk-Modules-Repo/FDE
NFSInjector
https://github.com/Magisk-Modules-Repo/nfsinjector/

**Comment by topjohnwu** [comment]
https://github.com/Magisk-Modules-Repo/FDE/issues/3
https://github.com/Magisk-Modules-Repo/nfsinjector/issues/6
