### ISSUE TITLE
BlueFrag Mitigation?

### ISSUE THREAD

**Issue by gordol** [Magisk-Modules-Repo/submission#652]
I've been trying to think of ways to mitigate BlueFrag in userspace... if we have root, it seems like we should be able to patch this, even on older devices that won't even receive security updates.

Does anyone have any thoughts about this?

**Comment by skittles9823** [comment]
This isn't really the place to discuss this but I'll leave it open in case anyone has thoughts on the matter.

If you'd like a more direct place to talk about module development you can join my telegram group [here](https://t.me/joinchat/GX3GuEsMEvlbm3bEWzYOKQ)

Alternatively I've created an XDA thread to discuss the same topics over [here](https://forum.xda-developers.com/apps/magisk/announcement-telegram-magisk-module-t3846678)

**Comment by gordol** [comment]
Appreciate it. I already searched the XDA forums and found only one hit for BlueFrag, and it's not a relevant discussion, so I figured it would fit here.

**Comment by topjohnwu** [comment]
Closed as this has nothing related to do with submission :)
