### ISSUE TITLE
[Submission] Wikipedia Hosts

### ISSUE THREAD

**Issue by AnClark** [Magisk-Modules-Repo/submission#69]
https://github.com/anclark/wikipedia-hosts

**Comment by ATechnoHazard** [comment]
This is too simple of a module to be accepted. There are other modules out there like [this](https://github.com/Magisk-Modules-Repo/energizedprotection) which offer more options and is more than just adding a few entries to the hosts file.

Closing.

**Comment by Didgeridoohan** [comment]
The [documentation clearly states](https://github.com/Magisk-Modules-Repo/submission#what-will-not-be-approved) that modules that only consist of a simple boot script won't be accepted to the repo.

**Comment by AnClark** [comment]
No wonder...

**Comment by sjayminsgithub** [comment]
@AnClark Between, did you realize that you must Magic Mount (or bind mount) hosts file first, or else it will modify the actual hosts file residing in the real system partition ??
Your module does not comply with systemless approach of Magisk, that's one more reason as to why it was rejected.

**Comment by AnClark** [comment]
Any document for systemless hosts file?

**Comment by Didgeridoohan** [comment]
If the systemless hosts option in the Manager settings is activated it doesn't matter if you edit /system/etc/hosts, but if it isn't you're editing /system (big no-no).

To be sure that it's a systemless modification you need to edit /sbin/.core/img/.core/hosts. If that file is present, systemless hosts is activated automatically and the hosts file is Magic Mounted over /system/etc/hosts.
