### ISSUE TITLE
[submissions] Jancox Tool Unpack/Repack ROMs

### ISSUE THREAD

**Issue by wahyu6070** [Magisk-Modules-Repo/submission#700]
https://github.com/Wahyu6070/Jancox-tool-android

**Comment by androidacy-user** [comment]
Is magisk really necessary for this?

**Comment by wahyu6070** [comment]
yes magisk can by installing and uninstalling easily

**Comment by androidacy-user** [comment]
> yes magisk can by installing and uninstalling easily

That's not really magisk's reason to exist tho

**Comment by wahyu6070** [comment]
maybe the reason why this needs to be a magisk is to make it easier to update with magisk manager and system/bin/jancox or jancox_menu system scripts to be systemless
