### ISSUE TITLE
 [Submission].

### ISSUE THREAD

**Issue by enweazudaniel** [Magisk-Modules-Repo/submission#703]
Hello want to submit Universal kernel module

**Comment by enweazudaniel** [comment]
https://github.com/enweazudaniel/Universal-Kernel-Tweaks/blob/master/UKTV1.2.zip

**Comment by osm0sis** [comment]
Kernel tweaks modules are no longer being accepted on the official repo. You can close this.

**Comment by osm0sis** [comment]
Closing time.

**Comment by osm0sis** [comment]
This will auto-close shortly anyway, but again, kernel tweaks modules are no longer being accepted, so please do not resubmit.

**Comment by enweazudaniel** [comment]
Sorry for my late reply... No problem
