### ISSUE TITLE
[Submission] JoyPixels

### ISSUE THREAD

**Issue by yhchen0906** [Magisk-Modules-Repo/submission#709]
https://github.com/yhchen0906/joypixels

**Comment by 1mad1** [comment]
https://github.com/Magisk-Modules-Repo/Fontchanger

**Comment by yhchen0906** [comment]
> https://github.com/Magisk-Modules-Repo/Fontchanger

Fontchanger enables users to customize fonts and emojis while joypixels only allows replacing emojis.
However, Fontchanger has some overhead for users that does not need that much functionality.
1. Fontchanger requires a much longer time to install than joypixels.
2. Fontchanger requires manual configuration after installation, while this is not needed for joypixels.
3. Fontchanger requires two reboots while joypixels only require one.
Joypixels is suited for users who only needs to replace emojis. With easy installation which has less overhead and requires less effort.

**Comment by osm0sis** [comment]
Fontchanger is preferred in place of all other font/emoji modules, so this won't be accepted to the official repo. Please close.
