### ISSUE TITLE
[Submission] Magisk module to update adreno 300 series driver to latest developer preview

### ISSUE THREAD

**Issue by multiwirth** [Magisk-Modules-Repo/submission#711]
https://github.com/multiwirth/adreno-3xx-developer-driver

**Comment by multiwirth** [comment]
This module will update the Adreno 3xx gpu driver to the latest developer preview from Qualcomm.
Since this is a magisk module, it will easily survive OTA updates (LineageOS Updater).

**Comment by osm0sis** [comment]
https://github.com/Magisk-Modules-Repo/adreno-dev has this covered, and allows users to use the build of Adreno drivers they prefer (latest is not always greatest and Adreno-Nexus5-MMB29Q.zip and Adreno-Nexus7-MMB29Q.zip were the last that worked well).

**Comment by multiwirth** [comment]
mhh yeah you might be right.
So since there´s already a module, this one seems obsolete.
However, the version this one comes with got good and bad feedback.
Someone had performance issues while another guy experienced a smoother UI.
