### ISSUE TITLE
[Submission] ctpixel4 or China Telecom Enabler for Pixel 4

### ISSUE THREAD

**Issue by yangzhaofeng** [Magisk-Modules-Repo/submission#716]
https://github.com/yangzhaofeng/ctpixel4

This module enables Pixel 4/XL devices support China Telecom.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/82026692-652c9180-9693-11ea-8f44-fa53bcf70762.png)

**Comment by yangzhaofeng** [comment]
This module should work for most devices starting with Android 9, though it is mainly designed for Pixel 4. Do I need to write a list of compatible devices?

**Comment by MarcAnt01** [comment]
No, you need to read README and close this issue by yourself, since this kind of modules won't be approved

**Comment by yangzhaofeng** [comment]
@MarcAnt01 I mean this module can be optimized to run on most new devices.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 I mean this module can be optimized to run on most new devices.

I don't think there will be any problems if it can run on every device, but according to your title it is limited to Pixel 4/4XL
