### ISSUE TITLE
[Help needed] Force-push confused build server (I think)

### ISSUE THREAD

**Issue by nift4** [Magisk-Modules-Repo/submission#721]
Hi, I am the maintainer of microG Installer Revived (https://GitHub.com/Magisk-Modules-Repo/microG_Installer).
I force-pushed to the repository to unify the commit history with my development copy of the repo and now my module disappeared from the Magisk Manager. Can someone fix that, please?

**Comment by skittles9823** [comment]
Did the ID in module.prop change? That's normally the cause of hiccups like that. Looks like the G in microG may have changed to lower case?

**Comment by nift4** [comment]
It didn't change. The id comes from the original project and always was lowercase.

**Comment by skittles9823** [comment]
Huh that's weird as the repo url has the capital G and it takes that from the module ID 🤔

**Comment by nift4** [comment]
I manually renamed that long ago (and it worked) :P

**Comment by topjohnwu** [comment]
I can find the module through the app, no issues on my end
