### ISSUE TITLE
OnePlus Battery Saver

### ISSUE THREAD

**Issue by peterroth** [Magisk-Modules-Repo/submission#845]
Hi,
I'd like to apply with OnePlus Battery Saver, available here: https://github.com/peterroth/OnePlusBatterySaver

It can toggle the status of different OnePlus packages to save some battery, using a nice menu system.

**Comment by androidacy-user** [comment]
This is more device specific and probably won't be accepted fyi

**Comment by peterroth** [comment]
Other than that, noone monitors this repo and accepts the submissions. The Volume Steps Plus was also closed, without interaction.
