### ISSUE TITLE
I give up. Can't figure out why I always get Error: Request failed with status code 404

### ISSUE THREAD

**Issue by newbit1** [Magisk-Modules-Repo/submission#890]
Any idea what I am doing wrong to get this pass your bot? The Repo does exist and
is reachable with this link.

This Module is for AVDs only. It injects the overall missing android.hardware.usb.host.xml file to the Emulator to gain access for USB Devices with the new USB Pass Through feature. https://github.com/newbit1/usbhostpermissons

 MagiskBot commented 1 minute ago

Bad Request: https://github.com/newbit1/usbhostpermissons
Reason: Error: Request failed with status code 404

**Comment by newbit1** [comment]
It looks like I had to rename the branch from main to master.
But now I've got this new module error message.
New module submissions are required to follow the new module installer format. Instructions on how to create new modules with the new format is available in this page: Developer Guides.

**Comment by crok** [comment]
Then.. follow the guide.. it's actually a link to the guide.

**Comment by newbit1** [comment]
I already Did, at least I thought so!
Just double checking now...

**Comment by newbit1** [comment]
Got it, the optional customize.sh was still called install.sh
now it is open for a moderator review!
Thanks!!

**Comment by logmd** [comment]
should get the default branch naming to main and support master, better practices and removing racially incorrect terms from our code bases :)
