### ISSUE TITLE
@user1121114685

### ISSUE THREAD

**Issue by user1121114685** [Magisk-Modules-Repo/submission#955]
@user1121114685 
Firstly, please know that rules are for reference, moderators are supposed to decide on their own whether to approve or not. What is the human intelligence intender for otherwise ??

_Originally posted by @ghost in https://github.com/Magisk-Modules-Repo/submission/issues/23#issuecomment-430252442_

human intelligence Makes me happy, I am glad to see this issue today.

**Comment by patpolster** [comment]
> @user1121114685
> Firstly, please know that rules are for reference, moderators are supposed to decide on their own whether to approve or not. What is the human intelligence intender for otherwise ??
> 
> _Originally posted by @ghost in [#23 (comment)](https://github.com/Magisk-Modules-Repo/submission/issues/23#issuecomment-430252442)_
> 
> human intelligence Makes me happy, I am glad to see this issue today.
