### ISSUE TITLE
 [Submission] DocumentsUI-Replacer

### ISSUE THREAD

**Issue by ph4n70m-404** [Magisk-Modules-Repo/submission#976]
https://github.com/ph4n70m-404/DocumentsUI-Replacer

**Comment by gloeyisk** [comment]
Does this module really works for universal?
How about those deodexed ROMs that contains `oats` or something?

**Comment by ph4n70m-404** [comment]
So far I've tested it on roms like evo x and dotos and it worked however i had a weird issue with motorola stock a11 where the standard documentsui wasn't replaced but I am pretty sure thats because of project mainline however I don't know for sure

**Comment by ph4n70m-404** [comment]
using mobile and accidentally pressed the wrong button trying to comment lmao why is the close with comment bigger

**Comment by ph4n70m-404** [comment]
Went ahead and just made it a singular file because its easier for some of the other stuff i had in mind and it should stop any problems like that from arising.

**Comment by ph4n70m-404** [comment]
Closing because the magisk module repo is no longer part of the app and this has been open for a few months without it being either accepted or denied.
