### ISSUE TITLE
Bad Request: Reason: Error: Request failed with status code 404

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/submission#998]
I tried to submit a module 2 times and the bot returned me:
> Bad Request: https://github.com/mistergoliath41/OpenDNS4Magisk
> Reason: Error: Request failed with status code 404

**Comment by ghost** [comment]
Can these two issues be removed ?
https://github.com/Magisk-Modules-Repo/submission/issues/997
https://github.com/Magisk-Modules-Repo/submission/issues/996

**Comment by gjf** [comment]
I have the same issue. A month or so I have observed Github was not accessible by some providers. Looks like the bot operates with one of such providers.
The only way to fix is to try to submit in a next several days... and again and again.
Unfortunately with the stop of Magisk development looks like the management of modules is also downgraded...
